name: CI/CD

on:
  push:
    branches: [master]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        env:
          SECRET_KEY: ${{secrets.SECRET_KEY}}
          DEBUG: ${{secrets.DEBUG_VALUE}}
          ALLOWED_HOSTS: ${{secrets.ALLOWED_HOSTS}}
      - run: |
          echo before
          echo $DEBUG
          export DEBUG=DEBUG
          export SECRET_KEY=SECRET_KEY
          export ALLOWED_HOSTS=ALLOWED_HOSTS
          echo after
          echo $DEBUG
          python manage.py test
  build:
    name: build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/money-handler-api:v1
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.0.0
        with:
          heroku_api_key: ${{secrets.HEROKU_API}}
          heroku_app_name: "money-handler-api"
          heroku_email: "zigrasv@protonmail.com"
          usedocker: true
